title: Sampath Reddy Vengate # your name (or website title) here
logo: "/images/cover_pict.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A self-driven individual with an objective of lifelong learning! 
  <br><br>
  With this (though fancy sounding) line in mind, I set out to explore the world of Science & Technology and I have to say that it only gets stronger every passing day. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sampath-reddy-vengate/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
